# Generated by Django 5.2 on 2025-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='convert_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
